[2025-09-21T16:27:13.152+0330] {processor.py:186} INFO - Started process (PID=30913) to work on /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-21T16:27:13.153+0330] {processor.py:914} INFO - Processing file /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-21T16:27:13.156+0330] {logging_mixin.py:190} INFO - [2025-09-21T16:27:13.155+0330] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-21T16:27:13.161+0330] {logging_mixin.py:190} INFO - [2025-09-21T16:27:13.160+0330] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-21T16:27:13.161+0330] {logging_mixin.py:190} INFO - [2025-09-21T16:27:13.161+0330] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-21T16:27:13.162+0330] {processor.py:927} WARNING - No viable dags retrieved from /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-21T16:27:13.175+0330] {processor.py:208} INFO - Processing /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-09-21T16:28:25.926+0330] {processor.py:186} INFO - Started process (PID=33472) to work on /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-21T16:28:25.928+0330] {processor.py:914} INFO - Processing file /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-21T16:28:25.932+0330] {logging_mixin.py:190} INFO - [2025-09-21T16:28:25.931+0330] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-21T16:28:25.937+0330] {logging_mixin.py:190} INFO - [2025-09-21T16:28:25.936+0330] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-21T16:28:25.938+0330] {logging_mixin.py:190} INFO - [2025-09-21T16:28:25.938+0330] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-21T16:28:25.938+0330] {processor.py:927} WARNING - No viable dags retrieved from /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-21T16:28:25.953+0330] {processor.py:208} INFO - Processing /home/ak/projects/nyc-taxi-etl/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
